baseURL = 'https://www.nobodyls.cn/'
languageCode = 'zh-cn'
title = 'Nobodyls 的技术日志'
theme = 'PaperMod'

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    env = "production"
    author = "Nobodyls"
    # 开启搜索功能
    ShowReadingTime = true
    ShowPageViews = true
    ShowShareButtons = true
    ShowCodeCopyButtons = true
    ShowToc = true
    [params.pageViews]
        enable = true
        provider = "vercount"
        script = "https://events.vercount.one/js"
    # 首页信息卡片
    [params.homeInfoParams]
        Title = "👋 欢迎来到我的技术空间"
        Content = "专注于 RL Infra、AI 协作与 Windows 开发避坑。这里记录了我从 'Nobody' 到 'Somebody' 的进化过程。"

    # 社交图标配置
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/LS-plan"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "📚 文章"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "🏷️ 标签"
        url = "/tags/"
        weight = 15
    [[menu.main]]
        identifier = "categories"
        name = "🗂️ 分类"
        url = "/categories/"
        weight = 18
    [[menu.main]]
        identifier = "search"
        name = "🔍 搜索"
        url = "/search/"
        weight = 20
